=== xsandyguo/dalgen/dalgen/src/main/resources/dtd/mybatis-table-config-1.0.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--
        table 下包含多个 column resultmap operation sql 相应说明见定义
        namespace    命名空间
        sqlname      sql名
        remark      说明
        sequence     oracle使用
        physicalName 物理表名,分库分表使用
        -->
        <!ELEMENT table (operation* | sql* | column* )+>
        <!ATTLIST table
                sqlname CDATA #IMPLIED
                sequence CDATA #IMPLIED
                physicalName CDATA #IMPLIED
                remark CDATA #IMPLIED
                >

        <!ELEMENT column EMPTY>
        <!ATTLIST column
                name CDATA #REQUIRED
                javatype CDATA #REQUIRED
                >

        <!--
        最定义操作, 根据这里生成对应的 操作
        name          name
        paging        分页设置  - 暂时没想好怎么扩展 -后续加上(思路,如果设置paging 则自动添加分页参数 不需要自己写limit 只需要写查询条件即可)
        paramtype     参数类型: object 会自动翻译为 生成的对象,primitive 根据字段类型生成
        multiplicity  one 返回对象,many 返回list, paging 返回分页
        resulttype    指定返回类型(Map)
        resultmap     指定使用哪个resultmap 不写则使用自动生成的resultMap
        timeout       设置超时时间
        auto           - 暂时没想好怎么用,设想新增字段时自动修复
        -->
        <!ELEMENT operation (#PCDATA | sql)*>
        <!ATTLIST operation
                name CDATA #REQUIRED
                paging CDATA #IMPLIED
                paramtype (object|primitive|parameterObject) #IMPLIED
                multiplicity (one|many|paging) #IMPLIED
                remark CDATA #IMPLIED
                >


        <!ELEMENT sql (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST sql
                id CDATA #IMPLIED
                >


        <!ELEMENT include EMPTY>
        <!ATTLIST include
                refid CDATA #REQUIRED
                >


        <!ELEMENT selectKey (#PCDATA | include)*>
        <!ATTLIST selectKey
                resultType CDATA #IMPLIED
                keyProperty CDATA #IMPLIED
                order (BEFORE|AFTER) #IMPLIED
                >

        <!-- - - - - - - - - - - - - - - - - - - - - - - - -
                         DYNAMIC ELEMENTS
          - - - - - - - - - - - - - - - - - - - - - - - - -->


        <!ELEMENT bind EMPTY>
        <!ATTLIST bind
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST trim
                prefix CDATA #IMPLIED
                prefixOverrides CDATA #IMPLIED
                suffix CDATA #IMPLIED
                suffixOverrides CDATA #IMPLIED
                >

        <!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #IMPLIED
                index CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

        <!ELEMENT choose (when* , otherwise?)>

        <!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST when
                test CDATA #REQUIRED
                >

        <!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >

=== xsandyguo/dalgen/petstore/dalgen/petstoredb/tables/payment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "mybatis-table-config-1.0.dtd">

<table sqlname="payment">

	<sql id="Payment_columns">
		id, uuid, amt, status, gmt_created, payment_time, pay_channel 
	</sql>

	<operation name="insert" paramtype="object">
		<sql>
			INSERT INTO payment (
	        	id ,uuid ,amt ,status ,gmt_created ,payment_time ,pay_channel 
	        ) VALUES (
	        	? ,? ,? ,? ,? ,? ,? 
	        )
		</sql>
	</operation>

	<operation name="delete">
		<sql>
	        DELETE FROM payment WHERE
	        id = ? 
		</sql>
	</operation>

	<operation name="update" paramtype="object">
		<sql>
	        UPDATE payment SET
		        uuid = ? ,amt = ? ,status = ? ,gmt_created = ? ,payment_time = ? ,pay_channel = ? 
	        WHERE
	        	id = ? 
		</sql>
	</operation>

	<operation name="updateIf" paramtype="object">
		<sql>
			UPDATE	payment
			<set>
				<if test="uuid != null">
					uuid = #{uuid} ,
				</if>
				<if test="amt != null">
					amt = #{amt} ,
				</if>
				<if test="status != null">
					status = #{status} ,
				</if>
				<if test="gmtCreated != null">
					gmt_created = #{gmtCreated} ,
				</if>
				<if test="paymentTime != null">
					payment_time = #{paymentTime} ,
				</if>
				<if test="payChannel != null">
					pay_channel = #{payChannel} 
				</if>
			</set>
			<where>
				id = ? 
			</where>
		</sql>
	</operation>

	<operation name="queryById" multiplicity="one">
		<sql>
	    	SELECT
		    <include refid="Payment_columns"/>
	        FROM payment
	        WHERE
		        id = ? 
		</sql>
	</operation>


    <operation name="queryByUuid" paramtype="primitive" multiplicity="one">
    	<sql>
	    	SELECT
	    	<include refid="Payment_columns"/>
	        FROM payment where uuid = ?
		</sql>
    </operation>

	<operation name="findPage" multiplicity="paging" paramtype="parameterObject">
		<sql>
			SELECT
			<include refid="Payment_columns"/>
			FROM payment
			<where>
				<if test="uuid != null">
					AND uuid = #{uuid}
				</if>
				<if test="amt != null">
					AND amt = #{amt}
				</if>
				<if test="status != null">
					AND status = #{status}
				</if>
				<if test="gmtCreated != null">
					AND gmt_created = #{gmtCreated}
				</if>
				<if test="paymentTime != null">
					AND payment_time = #{paymentTime}
				</if>
				<if test="payChannel != null">
					AND pay_channel = #{payChannel}
				</if>
			</where>
		</sql>
	</operation>

</table>

=== xsandyguo/dalgen/dalgen/tables/member.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "mybatis-table-config-1.0.dtd">

<table sqlname="member">
	<typeMappings>
		<typeMapping column="type" javaType="net.petstore.common.dal.enums.MemberTypeEnum" />
	</typeMappings>

	<sql id="Member_columns">
		id, vip_start, vip_end, sign_time, type, trial_start, trial_end 
	</sql>

	<operation name="insert" paramtype="object">
		<sql>
			INSERT INTO member (
	        	id ,vip_start ,vip_end ,sign_time ,type ,trial_start ,trial_end 
	        ) VALUES (
	        	? ,? ,? ,? ,? ,? ,? 
	        )
		</sql>
	</operation>

	<operation name="delete">
		<sql>
	        DELETE FROM member WHERE
	        id = ? 
		</sql>
	</operation>

	<operation name="update" paramtype="object">
		<sql>
	        UPDATE member SET
		        vip_start = ? ,vip_end = ? ,sign_time = ? ,type = ? ,trial_start = ? ,trial_end = ? 
	        WHERE
	        	id = ? 
		</sql>
	</operation>

	<operation name="updateIf" paramtype="object">
		<sql>
			UPDATE	member
			<set>
				<if test="vipStart != null">
					vip_start = #{vipStart} ,
				</if>
				<if test="vipEnd != null">
					vip_end = #{vipEnd} ,
				</if>
				<if test="signTime != null">
					sign_time = #{signTime} ,
				</if>
				<if test="type != null">
					type = #{type} ,
				</if>
				<if test="trialStart != null">
					trial_start = #{trialStart} ,
				</if>
				<if test="trialEnd != null">
					trial_end = #{trialEnd} 
				</if>
			</set>
			<where>
				id = ? 
			</where>
		</sql>
	</operation>

	<operation name="queryById" multiplicity="one">
		<sql>
	    	SELECT
		    <include refid="Member_columns"/>
	        FROM member
	        WHERE
		        id = ? 
		</sql>
	</operation>


	<operation name="findPage" multiplicity="paging" paramtype="parameterObject">
		<sql>
			SELECT
			<include refid="Member_columns"/>
			FROM member
			<where>
				<if test="vipStart != null">
					AND vip_start = #{vipStart}
				</if>
				<if test="vipEnd != null">
					AND vip_end = #{vipEnd}
				</if>
				<if test="signTime != null">
					AND sign_time = #{signTime}
				</if>
				<if test="type != null">
					AND type = #{type}
				</if>
				<if test="trialStart != null">
					AND trial_start = #{trialStart}
				</if>
				<if test="trialEnd != null">
					AND trial_end = #{trialEnd}
				</if>
			</where>
		</sql>
	</operation>

</table>

=== xsandyguo/dalgen/petstore/dalgen/petstoredb/tables/member.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "mybatis-table-config-1.0.dtd">

<table sqlname="member">
	<typeHandlers>
		<typeHandler handler="org.apache.ibatis.type.EnumOrdinalTypeHandler" javaType="com.answer.aal.entity.StatusEnum" />
		<typeHandler handler="org.apache.ibatis.type.EnumOrdinalTypeHandler" javaType="com.answer.aal.entity.SexEnum" />
	</typeHandlers>

	<typeMappings>
		<typeMapping columnName="sex" javaType="com.answer.aal.entity.SexEnum" />
	</typeMappings>

	<sql id="Member_columns">
		id, uuid, real_name, password, phone_number, age, qq_number, signup_date, wechat_uid, nick_name 
	</sql>

	<operation name="insert" paramtype="object">
		<sql>
			INSERT INTO member (
	        	id ,uuid ,real_name ,password ,phone_number ,age ,qq_number ,signup_date ,wechat_uid ,nick_name 
	        ) VALUES (
	        	? ,? ,? ,? ,? ,? ,? ,? ,? ,? 
	        )
		</sql>
	</operation>

	<operation name="delete">
		<sql>
	        DELETE FROM member WHERE
	        id = ? 
		</sql>
	</operation>

	<operation name="update" paramtype="object">
		<sql>
	        UPDATE member SET
		        uuid = ? ,real_name = ? ,password = ? ,phone_number = ? ,age = ? ,qq_number = ? ,signup_date = ? ,wechat_uid = ? ,nick_name = ? 
	        WHERE
	        	id = ? 
		</sql>
	</operation>

	<operation name="updateIf" paramtype="object">
		<sql>
			UPDATE	member
			<set>
				<if test="uuid != null">
					uuid = #{uuid} ,
				</if>
				<if test="realName != null">
					real_name = #{realName} ,
				</if>
				<if test="password != null">
					password = #{password} ,
				</if>
				<if test="phoneNumber != null">
					phone_number = #{phoneNumber} ,
				</if>
				<if test="age != null">
					age = #{age} ,
				</if>
				<if test="qqNumber != null">
					qq_number = #{qqNumber} ,
				</if>
				<if test="signupDate != null">
					signup_date = #{signupDate} ,
				</if>
				<if test="wechatUid != null">
					wechat_uid = #{wechatUid} ,
				</if>
				<if test="nickName != null">
					nick_name = #{nickName} 
				</if>
			</set>
			<where>
				id = ? 
			</where>
		</sql>
	</operation>

	<operation name="queryById" multiplicity="one">
		<sql>
	    	SELECT
		    <include refid="Member_columns"/>
	        FROM member
	        WHERE
		        id = ? 
		</sql>
	</operation>


    <operation name="queryByUuid" paramtype="primitive" multiplicity="one">
    	<sql>
	    	SELECT
	    	<include refid="Member_columns"/>
	        FROM member where uuid = ?
		</sql>
    </operation>

	<operation name="findPage" multiplicity="paging" paramtype="parameterObject">
		<sql>
			SELECT
			<include refid="Member_columns"/>
			FROM member
			<where>
				<if test="uuid != null">
					AND uuid = #{uuid}
				</if>
				<if test="realName != null">
					AND real_name = #{realName}
				</if>
				<if test="password != null">
					AND password = #{password}
				</if>
				<if test="phoneNumber != null">
					AND phone_number = #{phoneNumber}
				</if>
				<if test="age != null">
					AND age = #{age}
				</if>
				<if test="qqNumber != null">
					AND qq_number = #{qqNumber}
				</if>
				<if test="signupDate != null">
					AND signup_date = #{signupDate}
				</if>
				<if test="wechatUid != null">
					AND wechat_uid = #{wechatUid}
				</if>
				<if test="nickName != null">
					AND nick_name = #{nickName}
				</if>
			</where>
		</sql>
	</operation>

</table>

=== xsandyguo/dalgen/dalgen/src/main/resources/templates/table/dalgen_config/${sqlName^lower_case}.xml
<#assign className = table.className>
<#assign classNameLower = className?uncap_first>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "mybatis-table-config-1.0.dtd">

<table sqlname="${table.sqlName}">
	<#list table.columns as column>
	<#if column.sqlName?lower_case?contains('amount') && column.javaType?lower_case?contains('long')>
	<column name="${column.sqlName}" javatype="com.iwallet.biz.common.util.money.Money" />
	</#if>
	</#list>

	<sql id="${className}_columns">
		<#list table.columns as column>${column.sqlName}<#if column_has_next>,</#if> </#list>
	</sql>

	<operation name="insert" paramtype="object">
		<sql>
			INSERT INTO ${table.sqlName} (
	        	<#list table.columns as column>${column.sqlName} <#if column_has_next>,</#if></#list>
	        ) VALUES (
	        	<#list table.columns as column>? <#if column_has_next>,</#if></#list>
	        )
		</sql>
	</operation>

	<operation name="delete">
		<sql>
	        DELETE FROM ${table.sqlName} WHERE
	        <#list table.pkColumns as column>
	        ${column.sqlName} = ? <#if column_has_next> AND </#if>
			</#list>
		</sql>
	</operation>

	<operation name="update" paramtype="object">
		<sql>
	        UPDATE ${table.sqlName} SET
		        <#list table.notPkColumns as column>${column.sqlName} = ? <#if column_has_next>,</#if></#list>
	        WHERE
	        	<#list table.pkColumns as column>${column.sqlName} = ? <#if column_has_next> AND </#if></#list>
		</sql>
	</operation>

	<operation name="updateIf" paramtype="object">
		<sql>
			UPDATE	${table.sqlName}
			<set>
				<#list table.notPkColumns as column>
				<if test="${column.columnNameFirstLower} != null">
					${column.sqlName} = <#noparse>#{</#noparse>${column.columnNameFirstLower}} <#if column_has_next>,</#if>
				</if>
				</#list>
			</set>
			<where>
				<#list table.pkColumns as column>${column.sqlName} = ? <#if column_has_next> AND </#if></#list>
			</where>
		</sql>
	</operation>

	<operation name="queryById" multiplicity="one">
		<sql>
	    	SELECT
		    <include refid="${className}_columns"/>
	        FROM ${table.sqlName}
	        WHERE
				<#list table.pkColumns as column>
		        ${column.sqlName} = ? <#if column_has_next> AND </#if>
		        </#list>
		</sql>
	</operation>

    <#list table.columns as column>
    <#if column.unique && !column.pk>

    <operation name="queryBy${column.columnName}" paramtype="primitive" multiplicity="one">
    	<sql>
	    	SELECT
	    	<include refid="${className}_columns"/>
	        FROM ${table.sqlName} where ${column.sqlName} = ?
		</sql>
    </operation>
    </#if>
	</#list>

	<operation name="findPage" multiplicity="paging" paramtype="parameterObject">
		<sql>
			SELECT
			<include refid="${className}_columns"/>
			FROM ${table.sqlName}
			<where>
				<#list table.notPkColumns as column>
				<if test="${column.columnNameFirstLower} != null">
					AND ${column.sqlName} = <#noparse>#{</#noparse>${column.columnNameFirstLower}}
				</if>
				</#list>
			</where>
		</sql>
	</operation>

</table>
